[package]
name = "prediction_market"
version = "0.1.0"
description = "Binary prediction markets — mrgin protocol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "prediction_market"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
cross_margin = { path = "../cross_margin", features = ["cpi"] }
